# Generated by Django 5.2.1 on 2025-05-28 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='updated at')),
                ('business_name', models.CharField(blank=True, default='', help_text='Official business name for payment plans; optional until later completion', max_length=255, verbose_name='business name')),
                ('business_registration_number', models.CharField(blank=True, help_text='Required for financial compliance; must be unique when provided', max_length=20, null=True, verbose_name='registration number')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Must be True to allow merchant to create payment plans. Verified status can be set manually by an admin or automatically via a periodic task (e.g., KYC check).', verbose_name='verified status')),
                ('user', models.OneToOneField(help_text='Reference to the Merchant user account', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'merchant profile',
                'verbose_name_plural': 'merchant profiles',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('business_registration_number__isnull', True), _negated=True), fields=('business_registration_number',), name='unique_business_reg_number_if_not_null')],
            },
        ),
    ]
