# Generated by Django 5.2.1 on 2025-05-28 22:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='updated at')),
                ('credit_score', models.IntegerField(blank=True, help_text='External credit score; populate after credit check', null=True, validators=[django.core.validators.MinValueValidator(300, 'Minimum credit score is %(limit_value)s'), django.core.validators.MaxValueValidator(850, 'Maximum credit score is %(limit_value)s')], verbose_name='credit score')),
                ('score_status', models.CharField(choices=[('pending', 'Pending Validation'), ('approved', 'Validated'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current status of credit score validation', max_length=20, verbose_name='score status')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Can this customer use BNPL services?', verbose_name='active status')),
                ('user', models.OneToOneField(help_text='Reference to the Customer user account', on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'customer profile',
                'verbose_name_plural': 'customer profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
