# Generated by Django 5.2.1 on 2025-05-28 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(help_text='Descriptive name for this payment plan.', max_length=128, verbose_name='plan name')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total sum to be paid across all installments.', max_digits=12, verbose_name='total amount')),
                ('installment_count', models.PositiveSmallIntegerField(help_text='Total number of equal installments.', verbose_name='number of installments')),
                ('installment_period', models.PositiveSmallIntegerField(default=30, help_text='Interval in days between installments.', verbose_name='installment period (days)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Current lifecycle status of the plan.', max_length=10, verbose_name='status')),
                ('merchant', models.ForeignKey(help_text='The merchant user who owns this plan.', limit_choices_to={'user_type': 'merchant'}, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
