# Generated by Django 5.2.1 on 2025-05-28 23:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='updated at')),
                ('start_date', models.DateField(default=datetime.date.today, help_text='Date when the first installment is due.', verbose_name='start date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted')], default='active', help_text='Current lifecycle status of the installment plan.', max_length=10, verbose_name='status')),
                ('customer', models.ForeignKey(help_text='The customer associated with this installment plan.', limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(help_text='The payment plan template used to generate installments.', on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='plan.plan')),
            ],
            options={
                'verbose_name': 'installment plan',
                'verbose_name_plural': 'installment plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount due for this installment.', max_digits=12, verbose_name='amount')),
                ('due_date', models.DateField(help_text='Date when this installment is due.', verbose_name='due date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('late', 'Late'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current payment status of the installment.', max_length=10, verbose_name='status')),
                ('sequence_number', models.PositiveSmallIntegerField(help_text='Sequential position of this installment in the plan.', verbose_name='installment number')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when the installment was paid.', null=True, verbose_name='paid at')),
                ('installment_plan', models.ForeignKey(help_text='The associated installment plan.', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='installment.installmentplan')),
            ],
            options={
                'verbose_name': 'installment',
                'verbose_name_plural': 'installments',
                'ordering': ['sequence_number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='installment_amount_positive'), models.UniqueConstraint(fields=('installment_plan', 'sequence_number'), name='unique_installment_sequence_per_plan'), models.UniqueConstraint(fields=('installment_plan', 'due_date'), name='unique_due_date_per_plan')],
                'unique_together': {('installment_plan', 'sequence_number')},
            },
        ),
    ]
