# Generated by Django 5.2.1 on 2025-05-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together=set(),
        ),
    ]
