name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'backend/Dockerfile.dev'
      - 'backend/requirements*.txt'
      - '.github/workflows/docker-publish.yml'

jobs:
  push_to_docker_hub:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.dev
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/bnpl-backend:dev-${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/bnpl-backend:dev-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Logout from Docker Hub
        if: always()
        run: docker logout
